name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install mc-build
        run: npm i -g mc-build
      - name: Run mc-build
        run: cd datapack && mcb -build

      - name: Squash datapack
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: datapack
          artifact_name: datapack-raw
          force_include_files: pack.png
      - name: Download datapack-raw
        uses: actions/download-artifact@v3
        with:
          name: datapack-raw
      - name: Finish datapack
        run: |
          mv pack.zip <name>.zip
          zip -u <name>.zip LICENSE.txt README.md CHANGELOG.md

      - name: Squash resourcepack
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: resourcepack
          artifact_name: resourcepack-raw
      - name: Download resourcepack-raw
        uses: actions/download-artifact@v3
        with:
          name: resourcepack-raw
      - name: Finish resourcepack
        run: |
          mv pack.zip <name>.zip
          zip -u <name>-Resourcepack.zip LICENSE.txt README.md CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            CHANGELOG.md
            <name>.zip
            <name>-Resourcepack.zip

  release-github:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: <name> ${{github.ref_name}}
          body_path: CHANGELOG.md
          files: |
            <name>.zip
            <name>-Resourcepack.zip

  release-modrinth:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Publish on Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: <id>
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: <name> ${{github.ref_name}}
          files-primary: <name>.zip
          files-secondary: <name>-Resourcepack.zip
          version: ${{github.ref_name}}
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: datapack
          game-versions: |
            1.19
            1.19.1
            1.19.2
            1.19.3
